apiVersion: apps/v1
kind: Deployment
metadata:
  name: ads
  labels:
    app: ads
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ads
  template:
    metadata:
      labels:
        app: ads
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: ads
          image: "{{ .Values.image.registry }}/ads:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: "admin-port"
              containerPort: 15000
            - name: "ads-port"
              containerPort: 15128
          command: ['/ads']
          args: [
            "--verbosity", "trace",
            "--osmNamespace", "{{.Values.namespace}}",
            "--osmID", "{{.Release.Name}}",
            "--init-container-image", "{{.Values.image.registry}}/init",
            "--sidecar-image", "{{.Values.sidecarImage}}",
            "--webhookName", "osm-webhook-{{.Release.Name}}",
            "--certmanager", "{{.Values.certManager}}",
            "--vaultHost", "{{.Values.vault.host}}",
            "--vaultProtocol", "{{.Values.vault.protocol}}",
            "--vaultToken", "{{.Values.vault.token}}"
          ]
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
