apiVersion: v1
kind: Service
metadata:
  name: ads
  labels:
    app: ads
spec:
  ports:
    - name: ads-port
      port: 15128
      targetPort: 15128
    - name: sidecar-injector 
      port: 443
      targetPort: 9090
  selector:
    app: ads
