apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  annotations:
    prometheus.io/port: "7070"
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 7070
    protocol: TCP
    targetPort: 7070
  selector:
    app: prometheus-server
