apiVersion: apps/v1
kind: Deployment
metadata:
  name: osm-prometheus
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{.Values.prometheus.labelSelector}}
  template:
    metadata:
      labels:
        app: {{.Values.prometheus.labelSelector}}
    spec:
      containers:
      - name: prometheus
        ports:
        - containerPort: {{.Values.prometheus.port}}
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus/
        - --storage.tsdb.retention.time={{.Values.prometheus.retention.time}}
        - --web.listen-address=:{{.Values.prometheus.port}}
        image: prom/prometheus:v2.18.1
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/prometheus/
          name: prometheus-config-volume
        - mountPath: /prometheus/
          name: prometheus-storage-volume
      serviceAccountName: osm-prometheus-serviceaccount
      volumes:
      - name: prometheus-config-volume
        configMap:
          defaultMode: 420
          name: osm-prometheus-server-conf
      - name: prometheus-storage-volume
        emptyDir: {}
